
name: docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker install container
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps
      - name: Check weinote logs
        run: sleep 20; docker logs weinote
